apiVersion: v1
kind: Service
metadata:
  name: alexa-endpoint-service
  namespace: pcsongs
  labels:
    run: alexa-endpoint-deployment
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: port-5000
    targetPort: 5000
  selector:
    run: alexa-endpoint-deployment
  type: ClusterIP